

## Descripción
Let's decrypt this: [ciphertext](https://jupiter.challenges.picoctf.org/static/ee7e2388b45f521b285334abb5a63771/ciphertext)? Something seems a bit small.

## Solución
``` python
┌─[dantefx@dantefx-Inspiron5481]─[~/Descargas]
└──╼ $python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpy2
>>> 
>>> n=29331922499794985782735976045591164936683059380558950386560160105740343201513369939006307531165922708949619162698623675349030430859547825708994708321803705309459438099340427770580064400911431856656901982789948285309956111848686906152664473350940486507451771223435835260168971210087470894448460745593956840586530527915802541450092946574694809584880896601317519794442862977471129319781313161842056501715040555964011899589002863730868679527184420789010551475067862907739054966183120621407246398518098981106431219207697870293412176440482900183550467375190239898455201170831410460483829448603477361305838743852756938687673
>>> e=3
>>> c=2205316413931134031074603746928247799030155221252519872649649212867614751848436763801274360463406171277838056821437115883619169702963504606017565783537203207707757768473109845162808575425972525116337319108047893250549462147185741761825125 
>>> gmpy2.get_context().precision+2048
2101
>>> from Crypto.Util.number import long_to_bytes
>>> root, exact = iroot(c, e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'iroot' is not defined
>>> root, exact = gmpy2.iroot(c, e)
>>> root
mpz(13016382529449106065894479374027604750406953699090365388202874238148389207291005)
>>> print(long_to_bytes(root))
b'picoCTF{n33d_a_lArg3r_e_606ce004}'
>>> 

```
picoCTF{n33d_a_lArg3r_e_606ce004}